key_bindings:
  - {key: Return, mods: Control|Shift, action: SpawnNewInstance}
font:
  size: 13
  bold:
    family: "RobotoMono Nerd Font"
    style: "Bold"
  italic:
    family: "RobotoMono Nerd Font"
  normal:
    family: "RobotoMono Nerd Font"
    style: "Regular"
  glyph_offset:
    x: 0
    y: 0
  offset:
    x: 0
    y: 0
window:
  opacity: 0.95
  padding:
    x: 5
    y: 5
colors:
  primary:
    background: '#020202'
    foreground: '#CCCCFE'
  cursor:
    text: '#EEE9FC'
    cursor: '#EEE9FC'
  normal:
    black: '#100010'
    red: '#E965A5'
    green: '#B1F2A7'
    yellow: '#EBDE76'
    blue: '#A1AAF4'
    magenta: '#E192EF'
    cyan: '#B3F4F3'
    white: '#EEE9FC'
  bright:
    black: '#6C3067'
    red: '#CA4474'
    green: '#74D672'
    yellow: '#F1CA4D'
    blue: '#B15AFF'
    magenta: '#C71CC9'
    cyan: '#85E5ED'
    white: '#CF98C1'
