key_bindings:
  - {key: Return, mods: Control|Shift, action: SpawnNewInstance}
font:
  size: 13
  bold:
    family: "RobotoMono Nerd Font"
    style: "Bold"
  italic:
    family: "RobotoMono Nerd Font"
  normal:
    family: "RobotoMono Nerd Font"
    style: "Regular"
  glyph_offset:
    x: 0
    y: 0
  offset:
    x: 0
    y: 0
window:
  opacity: 1
  padding:
    x: 5
    y: 5
colors:
  primary:
    background: '#020202'
    foreground: '#ccccfe'
  cursor:
    text: '0xeee9fc'
    cursor: '0xeee9fc'
  normal:
    black: '#100010'
    red: '#e965a5'
    green: '#b1f2a7'
    yellow: '#ebde76'
    blue: '#a1aaf4'
    magenta: '#e192ef'
    cyan: '#b3f4f3'
    white: '#eee9fc'
  bright:
    black: '#6c3067'
    red: '#ca4474'
    green: '#74d672'
    yellow: '#f1ca4d'
    blue: '#b15aff'
    magenta: '#c71cc9'
    cyan: '#85e5ed'
    white: '#cf98c1'
